- include/Reaction.hh
@lpgaff : quick fix, code needs iomanip header to compile
iomanip include is missing for std::setprecision in Reaction.cc
> Fix missing include iomanip

- Makefile
"make -j" coulc fail, since one target depends on two files made by the same rule. Reasonably new versions of GNU make understand several targets in one rule which seems to have fixed this.
> Fixed missing dep for "make -j".

- src/Histogrammer.cc
Extend the ex histogram axes to go to -5MeV (keeping same size per bin), so we can see Ti states if present.
> Extend ex histograms

- src/Converter.cc
Otherwise, as char, the character is printed, not the number.
> Print as (int) in error output.

- src/AutoCalibrator.cc
Now plotting residuals against ADC peak centroid channel rather than DetectedEnergy. Also added the full expression for effective variance of y data from https://pubs.aip.org/aapt/ajp/article/50/10/912/1051796/Least-squares-when-both-variables-have although this probably does not make a difference with tiny alpha particle energy errors.
> Bug in autocal residuals plot

- include/Histogrammer.hh
- src/Histogrammer.cc
Use the ISSEvts class to calculate the histogram bin limits for the z axis of the array. Previously there was a bug that took the centres of each strip and used those as the *limits* of the histogram bins, so everything was shifted in z by half of a strip.
> Update histogram limits for the z axis of the array

- src/Histogrammer.cc
so that the errors are stored and can be correctly propagated when a background subtraction is performed
> Set the Sumw2 method by default on histograms 

- src/Reaction.cc
By providing a double as default TEnv will read a double as value from the settings file.
Before a value of 1e9 in the input file would be read as integer and thus be truncated to 1 instead of 1.000.000.000 .
> Fix bug T1.Min

- calibration.dat
- include/Calibration.hh
- src/Calibration.cc
- src/EventBuilder.cc
Added another type of time walk correction "WalkType = 2" where you draw a TGraph over the time walk curve and evaluate the line to get the time walk for a particular energy. As you are evaluating an x value (energy) to get a y value (time) you must draw the 'J-curve' with the time walk as tdiff as a function of energy (i.e. plot the axes the other way round as it is currently). 
Save the TGraph in a root file and add the files into the calibration file, exactly the same as how EvZ and recoil cuts are read in, and the specific notation should be written as a comment in the calibration file itself.
As this simple line, time difference as a function of energy deltaT(E),  is just begin evaluated for a particular energy, no solving of functions or parameters are needed!
One thing to note is …
> Time walk correction TGraph Method 

- include/Reaction.hh
- src/Histogrammer.cc
- src/Reaction.cc
Users can now sort the mixed laser data as long as the Laser Status is in the DAQ and correctly mapped with the settings file. One can choose to sort only laser off data from within a file (LaserMode = 0), only laser on data (LaserMode = 1) or either laser on or laser off data (LaserMode = 2).
> Add laser mode flag for the users

- src/Settings.cc
- tests/dump_settings.good
Fixes spurious errors during test builds.  I sometimes got the value 10 instead.
However, this variable does not seem to be used, so a better fix might be to remove it altogether?
And - is the value 6 what was intended?
> n_array_side was not initialised since its setting was not retrieved

- src/Converter.cc
unsigned char give characters,  often unprintable=nothing.
> Print as unsigned long to see integer values.

- iss_sort.cc
Didn't work if the raw data wasn't downstream from where the iss_sort was run.  Now the path string is build the same way as constructed in do_convert
> Path string fix for consistency

- include/Histogrammer.hh
- include/Reaction.hh
- include/RootLinkDef.h
- reaction.dat
- src/EventBuilder.cc
- src/Histogrammer.cc
- src/Reaction.cc
Inspired by Han’s’ submission in #46 and now that I finally had a free afternoon to look at this, I have implemented the output tree requested by users in the summer.
This is very similar to the ‘rxtree’ by Hans, but the branches are a couple of new classes that contain the required variables, rather than one branch for each of the individual values. 
I might still be missing a couple of variables from the list. I missed out the time windows, because I guess if somebody is analysing from the tree, they’ll be making their own conditions on things like time. 
I need to think of a way to add the recoil data next, which is a bit tricky as there can be multiple recoils in an event. There’s a precedent for resolving this though, by adding a vector of events. Then we have to trust users to …
> Introduction of ‘rxtree’, output tree for reaction data

- .github/workflows/doxygen-gh-pages.yml
- Doxyfile.bak
- include/ISSEvts.hh
- include/Reaction.hh
- src/ISSEvts.cc
- src/Reaction.cc
- utils/elum_energy_calculator.cc
- utils/plot_from_rxtree.cc
- utils/z_to_angle_simulator.cc
Fix some bugs in the phi angle calculations and update the reaction tree to include module ID, row number, p-side ID and n-side ID for the array events. Still not got recoil events in there (because nobody has asked for them yet).
> Update to reaction tree and phi angle calculations

- include/Histogrammer.hh
- src/EventBuilder.cc
- src/Histogrammer.cc
This request makes a couple of small tweaks in the event builder, namely giving a channel zero instead of NaN if the back channel is above threshold and it stores the position in a variable so it only needs to be calculated one time. Some small changes to the _events.root histograms so the axes have labels in keV as well.
The largest addition is histograms in the *_hists.root files where different LUME histograms have been added, e.g. E vs x gated on and off EBIS and plots for individual detectors.
> LUME histograms

- src/EventBuilder.cc
- src/Settings.cc
This is a fix for issue #91 caused by the CdFinder algorithm trying to access the dE layer of the CD detector when the user declares that there are no layers!
Solution is to instantly return from CdFinder() if there GetNumberOfCDLayers() == 0...
Might be a more elegant way generally of calling or returning from the particle reconstruction algorithms if we have no events or detectors in place. But for now, fix it like this.
> Fix for issue #91

- src/EventBuilder.cc
- src/Histogrammer.cc
- src/Settings.cc
Michał spotted that the recoil gating in the histogrammer checked the time OR the energy, so in the case that you have more than one recoil in an event, you can get different particles passing each gate. Changed to specifically make this an AND condition.
> Recoil bug fix from Michał W

- src/Histogrammer.cc
in discussion with Michal we agreed that the prompt/random checks should not be exclusive, otherwise it messes up the weighting of the subtraction. If the multiplicity is large and the prompt are random time windows are large, then we would start throwing away events disproportionately. In particular, if the prompt and random windows are different sizes, we get really messed up... Can be reviewed with some data
> Remove prompt/random exclusivity checks

- include/EventBuilder.hh
- src/EventBuilder.cc
Added plots for sector and ring ID versus energy, similar to the array.
> Added channel ID vs energy plots for fission detectors.

- include/Converter.hh
- iss_sort.cc
- src/Converter.cc
This is inspired by Miniball, where a flag is used in the sorting to speed things up by taking events only within a 4 µs time window after the EBIS. The throws away a lot of background gammas at Miniball and speeds up the data sorting. Here is might throw away some noise events to help things.
To be used online only, a full sort should be done offline after the beam time to make sure no events get missed in this process.
> Add an ebis flag for sorting

- Makefile
Speedup ~ 20 %.  No difference in text output.
```
f96hajo@subfy05:~/2025/22Ne25$ time ../../q/ISSSort/bin/iss_sort -s ../calibrations/settings_stable_beam2025.dat -c ../calibrations/calibration_stable_beam2025.dat -r ../calibrations/reaction_stable_beam2025.dat -i /chalmers/groups/subexp/iss/2025/22Ne25/R69_0 -f -e -d sorted -ebis > out_orig.txt
real    1m25.763s
user    1m18.796s
sys     0m2.400s
f96hajo@subfy05:~/2025/22Ne25$ time ../../q/ISSSort/bin/iss_sort -s ../calibrations/settings_stable_beam2025.dat -c ../calibrations/calibration_stable_beam2025.dat -r ../calibrations/reaction_stable_beam2025.dat -i /chalmers/groups/subexp/iss/2025/22Ne25/R69_0 -f -e -d sorted -ebis > out_-O3.txt
real    1m9.335s
user    1m2.192s
sys     0m2.399s
f96hajo@subfy05:~/2025/22Ne25$ diff -u …
```
> Compile with -O3.

- include/Converter.hh
% is a remainder operator (apparently), and give negative output for negative input. Fix by adding and then doing % again.
Sorry for slowing down the ebis flag so much by getting more statistics :-)
Found while attempting to speed up data sorting by presorting the file.  That found ~ 3 times as many hits within ebis flag cut for R69_0:
```
f96hajo@subfy05:~/2025/22Ne25$ diff out_orig.txt out_modfix.txt -u
--- out_orig.txt        2025-06-26 20:09:40.156513457 +0200
+++ out_modfix.txt      2025-06-26 20:28:10.770062295 +0200
@@ -18,50 +18,50 @@
EBIS period detected = 49999120 ns
100%%
Building time-ordered index of events...
- Sorting: size of the sorted index = 4663451
100%        
+ Sorting: size of the sorted index = 13683409
100%        
Writing data and closing the file
+++ ISS …
```
> Fix ebis flag.
