ISOLDESolenoidalSpectrometer/ISSSort

- src/Converter.cc
- src/DataSpy.cc
- src/EventBuilder.cc
- src/Reaction.cc
Note: second commit untested.  (No data spy.)
> Silencing some compiler warnings.

- .github/workflows/ci-actions.yml
CI testing is can be nice to have.
This script can run as github actions.
My experience with github CI is very limited.  This was inspired from Hans' plutt program.
> Try a CI action file.

- include/AutoCalibrator.hh
- include/CommandLineInterface.hh
- include/Converter.hh
- include/DataPackets.hh
- include/DataSpy.hh
- include/EventBuilder.hh
- include/Histogrammer.hh
- include/ISSEvts.hh
- include/ISSGUI.hh
- include/Reaction.hh
- iss_sort.cc
- iss_sort.hh
- reaction.dat
- src/Histogrammer.cc
- src/Reaction.cc
This update adds the ELUM-Recoil time conditions to the reaction file for user control, and also makes and fills a complete set of time-random recoil histograms.
> Histogrammer updates

- src/EventBuilder.cc
Updated array PP/NN coincidence logic to only consider charge on neighbouring strips.
> Updated PP/NN coincidence logic to only consider neighbouring strips

- include/Histogrammer.hh
- src/Histogrammer.cc
I added center of mass angle TH1's and energy versus center of mass angle TH2's to the histogrammer class.
The center of mass angle ones are so I can obtain the detector efficiency (from simulation) with the same analysis methods as real data. The other ones are for comparing to the theoretical kinematics line.
> Add histograms

- src/Settings.cc
- tests/dump_settings.good
Reverts ISOLDESolenoidalSpectrometer/ISSSort#47
> Revert "n_array_side was not initialised since its setting was not retrieved"

- include/Settings.hh
- src/Settings.cc
- tests/dump_settings.good
- tests/dump_settings.txt
As an alternative to #47 - remove the unused setting variable.
> Remove the unused n_array_side.

- tests/test_settings.sh
User convenience in case of mismatch.
> Unified diff.  Mainly to tell which files are diff'ed in case of error.

- .dir-locals.el
@annakawecka Perhaps this can simplify our editing...
> Set tab stops to 4 spaces for Emacs.

- include/Settings.hh
- settings.dat
- src/EventBuilder.cc
- src/Reaction.cc
- src/Settings.cc
Option to perform the event builder with the time-walk correction already applied.
> Build with walk

- include/Settings.hh
- settings.dat
- src/Settings.cc
Three unrelated changes in `Settings.hh/cc` and `settings.dat`.
I have isolated the changes to the settings-related files in separete commits (`git revise -i origin/main` and `cut`), the shuffled them with `git rebase` to the beginning.  Squashed them all.  And then again `get revise ... -> cut` to split out these unrelated changes.
Hopefully it is easier to see if the individual changes are good this way.
If good - please merge :-)
> Non CD settings changes

- .github/workflows/doxygen-gh-pages.yml
> update doxygen workflow permissions

- .github/workflows/doxygen-gh-pages.yml
Trying in vain to get this doxygen action to work properly...
> update doxygen actions

- include/ISSEvts.hh
- include/RootLinkDef.h
- src/ISSEvts.cc
Not used yet, only introducing the classes.
> Introduce ISSSingleLayerDetectorEvt and ISSMultiLayerDetectorEvt.

- include/ISSEvts.hh
- include/RootLinkDef.h
- src/ISSEvts.cc
Please handle #80 first, then this should be really small.
> Minor ISSArrayEvt changes.

- src/EventBuilder.cc
> Avoid the vectors clear() calls, only do swaps.

- include/ISSEvts.hh
- src/EventBuilder.cc
- src/ISSEvts.cc
This is on top of #82 , please consider that first.
> ISSEvt - update to use ISSSingle/MultiLayerDetectorEvt.

- include/ISSEvts.hh
- include/RootLinkDef.h
- src/ISSEvts.cc
And the much-sought updates - part I - evt.
> Added CD event.

- include/EventBuilder.hh
- include/ISSEvts.hh
- include/RootLinkDef.h
- src/EventBuilder.cc
- src/ISSEvts.cc
Prt II - event building.  (Though not yet real CdFinder().)  This is on top of #84 .
> EventBuilder - Implementing CD events.

- include/EventBuilder.hh
- include/Settings.hh
- settings.dat
- src/EventBuilder.cc
- src/Settings.cc
this can build multiple hits and has a basic charge-sharing reconstruction, but there are not enough debugging histograms as yet...
Annoyingly, a lot of whitespace changes have been mixed up in this, so it looks a lot worse than it is. The substance is only the CdFinder algorithm and a few related variables being changed.
> A more sophisticated CdFinder algorithm is proposed

- include/Reaction.hh
- src/Reaction.cc
Made a function to read a TCutG from a root file and replace some code segments with the new function ReadCutFile.
> Cut function

- include/EventBuilder.hh
- include/Histogrammer.hh
- include/ISSEvts.hh
- iss_sort.cc
- src/EventBuilder.cc
- src/Histogrammer.cc
- src/ISSEvts.cc
First go at a hit map for the CD and some extra debugging histrograms for the LUME detectors in the event builder.
> Edits to LUME hists in event builder and hit map for CD

- .github/workflows/doxygen-gh-pages.yml
- include/EventBuilder.hh
- iss_sort.cc
- src/EventBuilder.cc
- src/Histogrammer.cc
Fixes to the DataSpy which was broken in recent updates over the winter.
Also a couple of LUME bugs in the histogrammer.
> DataSpy fixes

- include/Converter.hh
- include/EventBuilder.hh
- include/Settings.hh
- settings.dat
- src/Converter.cc
- src/EventBuilder.cc
- src/Settings.cc
- tests/dump_settings.good
add the mesytec pulsers in to the data stream and check for sync to the CAEN with histograms
> Mesytec sync check

- include/Settings.hh
- settings.dat
- src/Converter.cc
- src/EventBuilder.cc
- src/Settings.cc
This is in draft... It will be added to as we work through bugs and improvements
> Some Mesytec updates during the beam time

- include/Histogrammer.hh
- include/ISSEvts.hh
- include/Reaction.hh
- reaction.dat
- src/EventBuilder.cc
- src/Histogrammer.cc
- src/ISSEvts.cc
- src/Reaction.cc
- src/Settings.cc
Various gamma-ray histograms... More to come.
We now have some coincidences with array and "recoil" events, even if those are in the CD. Still need too add the fission events, but for the moment we just have 22Ne beam and no fission.
> Gamma-ray histograms

- include/Reaction.hh
- reaction.dat
- src/Histogrammer.cc
- src/Reaction.cc
Now users can set ranges for the CD and LUME detectors
> More user inputs for histogram ranges

- include/Converter.hh
The part of the update commit that restores count values in text output.
> fix up lost root file write before close

- src/Converter.cc
Seems like some members were not set when processing traces.
> Missing members.

- src/Converter.cc
- src/Histogrammer.cc
Compiler complained about variables possibly falling through available if's and not being uninited.
> Potential uninit
